name: Deploy to K8S PRD Cluster

on: 
  push:
    branches: main

  workflow_dispatch:

env:
  APP_NAME: send-mailbox-api
  AWS_REGION: us-east-2
  NAMESPACE: jfl-novo-app

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Secrets
      id: secret
      env:
        TEXT: "image publish"
      run: |
        mkdir /test && echo $TEXT >> /test/outpu.log
        zip test.zip /test
    
    - name: Upload output file
      uses: actions/upload-artifact@v2
      with:
        name: output-zip
        path: test.zip
  
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs:
    - publish
    steps:
    - name: Download a single artifact
      uses: actions/download-artifact@v2
      with:
        name: output-zip
